%YAML:1.0

# Topic name in rosbag
PointCloudTopic: "/livox/lidar"
ImageTopic: "/camera/color/image_raw"

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.0,   -1.0,   0.0,    0.0,
         0.0,  0.0,  -1.0,    0.0,
         1.0,   0.0,    0.0,    0.0,
         0.0,   0.0,    0.0,    1.0]
# Params for Canny Edge Extraction

Canny.gray_threshold: 10
Canny.len_threshold: 200

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 0.5 # 복셀 크기 0.5
Voxel.down_sample_size: 0.02 # down sampling할때 복셀 크기 0.02
Plane.min_points_size: 30 # plane segmentation할 때 필요한 최소 개수 30
Plane.normal_theta_min: 45 # normal끼리 곱했을 때 나오는 theta 최소 45
Plane.normal_theta_max: 135 # normal끼리 곱했을 때 나오는 theta 최대 135
Plane.max_size: 8
Ransac.dis_threshold: 0.02
Edge.min_dis_threshold: 0.03
Edge.max_dis_threshold: 0.06
