%YAML:1.0

# Topic name in rosbag
PointCloudTopic: "/livox/lidar"
# ImageTopic: "/camera/color/image_raw"
ImageTopic: "/cam0/image_raw"
ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d

# CVLab calibration  
  data: [1.0,   0.0,   0.0,    0.057,
         0.0,   0.0,   -1.0,    0.06,
         0.0,   1.0,  0.0,    -0.015,
         0.0,   0.0,    0.0,    1.0]
  # data: [0.998423, -0.0534074, -0.0172966, 0.170806,
  #        -0.0176511,-0.00617313,-0.999825,-0.0255069,
  #        0.0532913, 0.998554,-0.00710609,0.165712,
  #        0.0,   0.0,    0.0,    1.0]   

Undistort.img: 1  # 1 = 펴는거 0 안펴는거
Camera.width: 1280
Camera.height: 720
CameraMat: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [728.82816581 , 0.0,      640.4149533,
         0.0,      730.80422197,  367.38455889,
         0.0,           0.0,      1.0    ]
DistCoeffs: !!opencv-matrix
  rows: 1
  cols: 4
  dt: d
  data: [-0.0287829, -0.00999668, 0.00586593, -0.00268109]   
    
# Params for Canny Edge Extraction

Canny.gray_threshold: 20
Canny.len_threshold: 200

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 1.0
Voxel.down_sample_size: 0.02
Plane.min_points_size: 60
Plane.normal_theta_min: 30
Plane.normal_theta_max: 150
Plane.max_size: 5
Ransac.dis_threshold: 0.015
Ransac.iter_num: 200
Edge.min_dis_threshold: 0.03
Edge.max_dis_threshold: 0.06

# Params for color point clouds
Color.dense: 1
Color.intensity_threshold: 10