# Data path. adjust them!
common:
    image_path:  "/data/livox/multi/myimage"    # myimage/0.png, 1.png ...
    pcd_path:  "/data/livox/multi/mypcd"        # mypcd/0.pcd, 1.pcd ...
    result_path:  "/root/workspace/src/livox_camera_calib/extrinsic.txt"
    data_num: 4                                 # number of data

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [728.82816581 , 0.0,      640.4149533,
                    0.0,     730.80422197,  367.38455889,
                    0.0,     0.0,      1.0     ]
    dist_coeffs: [-0.0287829, -0.00999668, 0.00586593, -0.00268109, 0.0] 

# Calibration Parameters.!
calib:
    # calib_config_file: "/root/workspace/src/livox_camera_calib/config/config_indoor.yaml"
    calib_config_file: "/root/workspace/src/livox_camera_calib/config/cvlab_outdoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
