# Data path. origin
common:
    image_file: "/data/calib/images/1.bmp"
    pcd_file: "/data/calib/pcds/1.pcd"
    result_file: "/root/workspace/src/livox_camera_calib/result/c1.txt"

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [731.259227, 0.0, 630.246023,
                    0.0, 730.071969, 353.541195,
                    0.0, 0.0, 1.0]
    dist_coeffs: [-0.358663, 0.148861, 0.000282, 0.000402, 0.0] 

# Calibration Parameters.!
calib:
    # calib_config_file: "/root/workspace/src/livox_camera_calib/config/config_indoor.yaml"
    calib_config_file: "/root/workspace/src/livox_camera_calib/config/config_outdoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad